<?php
class AppointmentRepository{private mysqli $db;public function __construct(){$this->db=Database::getConnection();}
public function search(string $q='',string $sort='a.id',string $dir='DESC',int $limit=10,int $offset=0):array{$allowed=['a.id','a.schedule','p.name'];if(!in_array($sort,$allowed,true)){$sort='a.id';}$dir=strtoupper($dir)==='ASC'?'ASC':'DESC';$rows=[];if($q!==''){$sql="SELECT a.id,a.schedule,a.notes,p.name as patient_name FROM appointments a JOIN patients p ON p.id=a.patient_id WHERE p.deleted_at IS NULL AND (p.name LIKE ? OR a.notes LIKE ?) ORDER BY $sort $dir LIMIT ? OFFSET ?";$st=$this->db->prepare($sql);$like='%'.$q.'%';$st->bind_param('ssii',$like,$like,$limit,$offset);}else{$sql="SELECT a.id,a.schedule,a.notes,p.name as patient_name FROM appointments a JOIN patients p ON p.id=a.patient_id WHERE p.deleted_at IS NULL ORDER BY $sort $dir LIMIT ? OFFSET ?";$st=$this->db->prepare($sql);$st->bind_param('ii',$limit,$offset);} $st->execute();$res=$st->get_result();while($r=$res->fetch_assoc()){$rows[]=$r;}$st->close();return $rows;}

public function count(string $q=''):int{if($q!==''){$sql='SELECT COUNT(*) AS c FROM appointments a JOIN patients p ON p.id=a.patient_id WHERE p.deleted_at IS NULL AND (p.name LIKE ? OR a.notes LIKE ?)';$st=$this->db->prepare($sql);$like='%'.$q.'%';$st->bind_param('ss',$like,$like);}else{$sql='SELECT COUNT(*) AS c FROM appointments a JOIN patients p ON p.id=a.patient_id WHERE p.deleted_at IS NULL';$st=$this->db->prepare($sql);} $st->execute();$res=$st->get_result();$c=(int)($res->fetch_assoc()['c']??0);$st->close();return $c;}

public function findById(int $id):?array{$sql='SELECT a.*,p.name as patient_name FROM appointments a JOIN patients p ON p.id=a.patient_id WHERE a.id=?';$st=$this->db->prepare($sql);$st->bind_param('i',$id);$st->execute();$res=$st->get_result();$row=$res->fetch_assoc();$st->close();return $row?:null;}

public function create(array $d):int{$sql='INSERT INTO appointments (patient_id,doctor_id,schedule,notes) VALUES (?,?,?,?)';$st=$this->db->prepare($sql);$pid=(int)$d['patient_id'];$did=(int)$d['doctor_id'];$schedule=$d['schedule'];$notes=$d['notes']??null;$st->bind_param('iiss',$pid,$did,$schedule,$notes);$st->execute();$id=(int)$st->insert_id;$st->close();return $id;}

public function update(int $id,array $d):bool{$sql='UPDATE appointments SET patient_id=?,doctor_id=?,schedule=?,notes=? WHERE id=?';$st=$this->db->prepare($sql);$pid=(int)$d['patient_id'];$did=(int)$d['doctor_id'];$schedule=$d['schedule'];$notes=$d['notes']??null;$st->bind_param('iissi',$pid,$did,$schedule,$notes,$id);$ok=$st->execute();$st->close();return $ok;}

public function delete(int $id):bool{$st=$this->db->prepare('DELETE FROM appointments WHERE id=?');$st->bind_param('i',$id);$ok=$st->execute();$st->close();return $ok;}}
